"""Versioned records used by the offline TurnBench boundary."""

from .candidates import PauseCandidate, extract_candidates
from .auto_schema import (
    AutoPrediction,
    CANDIDATE_SCHEMA,
    PREDICTION_SCHEMA,
    REFERENCE_SCHEMA,
    REFERENCE_SOURCE,
    DiarBenchCandidate,
    DiarBenchReference,
    read_candidates,
    read_predictions,
    read_references,
    write_candidates,
    write_predictions,
    write_references,
)
from .diarbench import convert_diarbench_sample
from .report import score_inputs
from .schema import (
    Annotation,
    DecisionLabel,
    EVENT_SCHEMA,
    LABEL_SCHEMA,
    ProviderTrace,
    RECORDING_SCHEMA,
    Recording,
    SchemaError,
    SourceTurn,
    TraceEvent,
    read_jsonl,
    write_jsonl,
)
from .score import DecisionScore, aggregate, bootstrap_by_recording, nearest_rank, score_decision

__all__ = [
    "Annotation",
    "AutoPrediction",
    "CANDIDATE_SCHEMA",
    "DecisionLabel",
    "DecisionScore",
    "DiarBenchCandidate",
    "DiarBenchReference",
    "EVENT_SCHEMA",
    "LABEL_SCHEMA",
    "ProviderTrace",
    "PauseCandidate",
    "PREDICTION_SCHEMA",
    "RECORDING_SCHEMA",
    "REFERENCE_SCHEMA",
    "REFERENCE_SOURCE",
    "Recording",
    "SchemaError",
    "SourceTurn",
    "TraceEvent",
    "aggregate",
    "bootstrap_by_recording",
    "convert_diarbench_sample",
    "extract_candidates",
    "nearest_rank",
    "read_jsonl",
    "read_candidates",
    "read_predictions",
    "read_references",
    "score_decision",
    "score_inputs",
    "write_jsonl",
    "write_candidates",
    "write_predictions",
    "write_references",
]
